### ISSUE TITLE
I modified my device using torngat, app got removed now can't return to stock.

### ISSUE THREAD

**Issue by ryannairj** [1GamerDev/Torngat#3]
So I have an iPhone 7 Plus on iOS 10.3.1 and I used the torngat app for some customization. Now because the 7 days are up the app no longer works and I can't redownload because the new versions don't support this os, I can't find an old version ipa. So now I am stuck with these customizations I would like to remove and change. Any help!

**Comment by 1GamerDev** [comment]
This isn't an issue.  To be clear, I only care about bugs or code-related issues that are submitted here.  Contact me on Twitter about this type of stuff.
This is the one and only time I'll reply to an 'issue' like this since I'm already writing a reply.
Beta 3.2.3 can be found at http://torngat.1gamerdev.rf.gd/Torngat_vB3.2.3.ipa

**Comment by ryannairj** [comment]
Thanks for that. That basically saved my phone! Any chance that you have the source-code for that version?
